//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioteqSofiya931.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChitatelBilet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChitatelBilet()
        {
            this.HistoryReadTicket = new HashSet<HistoryReadTicket>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Id_Employee { get; set; }
        public Nullable<int> Id_Chitatel { get; set; }
        public Nullable<System.DateTime> DateReg { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual Chitatel Chitatel { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryReadTicket> HistoryReadTicket { get; set; }
    }
}
