//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioteqSofiya931.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryReadTicket
    {
        public int ID { get; set; }
        public Nullable<int> Id_ChitatelBilet { get; set; }
        public Nullable<int> Id_Book { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual book book { get; set; }
        public virtual ChitatelBilet ChitatelBilet { get; set; }
    }
}
