//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioteqSofiya931.DBConnection
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryEntities1 : DbContext
    {
        public LibraryEntities1()
            : base("name=LibraryEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Avtor> Avtor { get; set; }
        public virtual DbSet<book> book { get; set; }
        public virtual DbSet<Chitatel> Chitatel { get; set; }
        public virtual DbSet<ChitatelBilet> ChitatelBilet { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Hall> Hall { get; set; }
        public virtual DbSet<HistoryReadTicket> HistoryReadTicket { get; set; }
        public virtual DbSet<Izdanie> Izdanie { get; set; }
        public virtual DbSet<Janr> Janr { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
